language: csharp
solution: Melia.sln
branches:
  only:
    - master
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1a9843b31f10f292cf44
    on_success: change
    on_failure: always
    on_start: never
install:
  - nuget restore Melia.sln
  #- nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
  - wget http://aura-project.org/xunit.runners.1.9.2.zip
  - unzip xunit.runners.1.9.2.zip
script:
  - xbuild /p:Configuration=Release Melia.sln
  - mono --debug ./testrunner/xunit.runners.*/tools/xunit.console.clr4.exe ./src/Test.ChannelServer/bin/Release/Test.ChannelServer.dll
  - mono --debug ./testrunner/xunit.runners.*/tools/xunit.console.clr4.exe ./src/Test.Shared/bin/Release/Test.Shared.dll
